development:
  adapter: postgresql
  encoding: unicode 
  host: localhost
  database: overheard_development 
  pool: 5
  username: neilmarion
  password: root

test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: overheard_test 
  pool: 5
  username: neilmarion
  password: root
